### PR TITLE
Fix for Issue #80

### PR DESCRIPTION
**Pull request by omarsilva1**

### CODE REVIEW

**Comment by tmberthold** [comment]
Waiting for https://github.com/International-Data-Spaces-Association/IDS-ConfigurationManager-UI/issues/38 to stay compatible

**Review by ghost — CHANGES_REQUESTED** [review]
Needs also to be changed for Settings: Curator, Maintainer, Proxy-URL (ConnectorAPI)

image

**Comment by tmberthold** [comment]
Don't worry about the merge conflicts, I'll look at those once the other fields have been addressed as well ;)

**Comment by ob-silva** [comment]
I have updated the requested parameters.

**Review by ghost — APPROVED** [review]

**Pull request merged**
